version: "3.8"

services:
    app:
        container_name: app_avaliacao_de_experiencia
        build: .
        environment:
            BACKEND_SERVER: "docker-compose"
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
